services:
   mongo:
      container_name: mongo
      build:
         context: .
         target: development
         dockerfile: Dockerfile
      ports:
         - 27017:27017
      networks:
         - nexlehr
      environment:
         - MONGO_INITDB_REPLICA_SET_NAME=nexlehr
         - MONGO_INITDB_ROOT_USERNAME=root
         - MONGO_INITDB_ROOT_PASSWORD=root
      healthcheck:
         test: ['CMD', 'sh', '/security/replica.sh']
         interval: 10s
         timeout: 10s
         retries: 0
networks:
   nexlehr:
      name: system
      driver: bridge
